version: '3.9'

services:
  api:
    container_name: api
    restart: always
    build: .
    ports:
      - 3000:3000
    depends_on:
      - db
  db:
    container_name: db
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: backend-test
    volumes:
      - ./data:/data/postgres
volumes:
  pgdata: {}