version: '3.9'

services:
  api:
    container_name: api
    restart: always
    build: .
    ports:
      - ${API_PORT}:${API_PORT}
    depends_on:
      - db
  db:
    container_name: db
    image: postgres
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./data:/data/postgres
volumes:
  pgdata: {}